apiVersion: v1
kind: Pod
metadata:
  name: bigdata-demon
  namespace: bigdata
  labels:
    name: bigdata-demon
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master3
  containers:
  - image: registry.iop.com:5000/bigdata/demon:latest
    imagePullPolicy: Always
    name: bigdata-demon
    command:
      - /usr/local/bin/start.sh
    ports:
    - name: web
      containerPort: 8080
      protocol: TCP
    securityContext:
      privileged: true
    volumeMounts:
    - name: tz-config
      mountPath: /etc/localtime
  volumes:
  - name: tz-config
    hostPath:
      path: /usr/share/zoneinfo/Asia/Shanghai